# Compile, bundle, and upload application bundles
# to a cloud storage on each pull request to "main".
# https://help.github.com/actions

name: PR

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

env:
  CI: false
  # VERSION: ${{ github.event.pull_request.number }}
  PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      # - uses: actions/checkout@v2
      # - run: yarn install --immutable --immutable-cache

      - name: Authenticate on GCS
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          export_default_credentials: true
          project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_CLIENT_SECRET }}
